### PR TITLE
Update numpy version to 1.23.0

### PR DESCRIPTION
**Pull request by csh519**
There was a alert from dependantbot, so update the numpy version to 1.23.0.
https://github.com/Samsung/CredSweeper/security/dependabot/3

### CODE REVIEW

**Review by babenek — APPROVED** [review]
OK. The development requirements file is updated.

**Review by mykolaf — APPROVED** [review]
:+1:

**Review by kmnls — APPROVED** [review]

**Review by kmnls — CHANGES_REQUESTED** [review]
Probably, you should set 'numpy>=1.23.0'?
numpy<=1.23.0 will allow the installation of vulnerable 1.20 for example

**Comment by csh519** [comment]
> Probably, you should set 'numpy>=1.23.0'? numpy<=1.23.0 will allow the installation of vulnerable 1.20 for example

@kmnls 
Actually it is for python3.7.. For now python3.7 only support numpy 1.21.6. So I decided to use <= operator.
Anyway except python3.7 other python versions are trying to install numpy 1.23.0.


https://github.com/Samsung/CredSweeper/runs/7989758463?check_suite_focus=true
``` bash
ERROR: Could not find a version that satisfies the requirement numpy~=1.23.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0rc1, 1.20.0rc2, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0rc1, 1.21.0rc2, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
```

**Comment by babenek** [comment]
> @kmnls Actually it is for python3.7.. For now python3.7 only support numpy 1.21.6. So I decided to use <= operator. 

maybe ~= ?

**Comment by babenek** [comment]
even ~=1.22 might fix the issue https://github.com/Samsung/CredSweeper/security/dependabot/3

**Comment by csh519** [comment]
> > @kmnls Actually it is for python3.7.. For now python3.7 only support numpy 1.21.6. So I decided to use <= operator.
> 
> maybe ~= ?

@babenek 
I try to set operator to ~= at first time but it failed. Please check https://github.com/Samsung/CredSweeper/pull/199/commits/3301f680dc13f57b1b9fd9778a24eb36c6e2cae0.

**Comment by csh519** [comment]
> even ~=1.22 might fix the issue https://github.com/Samsung/CredSweeper/security/dependabot/3

@babenek 
Yes, you're right. But I thought it would be good to use latest version that checked it works fine. So I choose 1.23.0.

**Comment by babenek** [comment]
Actually, for Python3.7 the NymPy v1.21.6 is installed in release mode
2022-08-24T07:41:40.7247820Z Collecting numpy
2022-08-24T07:41:40.7399400Z   Downloading numpy-1.21.6-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)
So, if the issue still exist - the check for Python3.7 might be skipped in CI ...

**Comment by csh519** [comment]
> Actually, for Python3.7 the NymPy v1.21.6 is installed in release mode 2022-08-24T07:41:40.7247820Z Collecting numpy 2022-08-24T07:41:40.7399400Z Downloading numpy-1.21.6-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB) So, if the issue still exist - the check for Python3.7 might be skipped in CI ...

@babenek 

Yes, it's correct. Skipping python3.7 is one of the best way to resolve this issue..
But in the same time it means *CredSweeper will not support python3.7*. I worried about it, therefore I just change the required version of numpy for workaround dependantbot from Github.

**Comment by babenek** [comment]
[NumPy 1.22.0 Release Notes](https://numpy.org/devdocs/release/1.22.0-notes.html):
The Python versions supported in this release are 3.8-3.10, Python 3.7 has been dropped.
:(

**Review by kmnls — APPROVED** [review]
Agree

**Comment by kmnls** [comment]
Probably we should add to README that it python 3.8+ should be preferred, shouldn't we?

**Comment by csh519** [comment]
> Probably we should add to README that it python 3.8+ should be preferred, shouldn't we?

@kmnls 

Yes, we should decide to stop the support of python3.7.

**Pull request merged**
