### PR TITLE
Add config section to readme

### PR DESCRIPTION
**Pull request by csh519**
There was no config section on `Readme`, so I added config section for better user experience.

Some users will want to modify the config quickly and it may help them.

### CODE REVIEW

**Comment by csh519** [comment]
@babenek 
As I checked the ActionTest was finished successfully at (#162).
But it is failed now.. https://github.com/Samsung/CredSweeper/runs/7573579031?check_suite_focus=true
Could you please check this?

**Comment by babenek** [comment]
@csh519 #165 - main was updated and found items should be matched SAMPLES_POST_CRED_COUNT: int = 18

**Review by babenek — CHANGES_REQUESTED** [review]
Please rebase the PR commits after v1.4.1

**Review by babenek — APPROVED** [review]
OK. The same changes after rebase

**Review by kmnls — APPROVED** [review]

**Pull request merged**
