### PR TITLE
Add Firebase rule

### PR DESCRIPTION
**Pull request by gy741**
Hello,

Added Firebase detection rules.

```
hack@hack:~$ cat strings.txt 
    <string name="firebase_database_url">https://api-project-615509201123.firebaseio.com</string>
    <string name="firebase_database_url">https://api-project-615509201123.firebaseapp.com</string>
```

```
hack@hack:~$ python3 -m credsweeper --path /home/hack/strings.txt --rule /home/hack/config.yaml 
rule: Firebase io Token / severity: high / line_data_list: [line : '    <string name="firebase_database_url">https://api-project-615509201123.firebaseio.com</string>' / line_num : 1 / path : /home/hack/strings.txt / value: 'api-project-615509201123.firebaseio.com' / entropy_validation: True] / api_validation: NOT_AVAILABLE / ml_validation: NOT_AVAILABLE
rule: Firebase APP Token / severity: high / line_data_list: [line : '    <string name="firebase_database_url">https://api-project-615509201123.firebaseapp.com</string>' / line_num : 2 / path : /home/hack/strings.txt / value: 'api-project-615509201123.firebaseapp.com' / entropy_validation: True] / api_validation: NOT_AVAILABLE / ml_validation: NOT_AVAILABLE
```

Thanks.

Ref: https://hackerone.com/reports/1065134

### CODE REVIEW

**Comment by gy741** [comment]
It would be nice to have an "or" keyword in the rules.
Then, duplicate rules can be merged into one.

```
- name: Firebase Token
  severity: high
  type: pattern
  values:
   - (?P<value>[a-z0-9.-]+\.firebaseio\.com)
   - (?P<value>[a-z0-9.-]+\.firebaseapp\.com)
  filter_type: GeneralPattern
  use_ml: false
  validations: []
```

**Comment by csh519** [comment]
> It would be nice to have an "or" keyword in the rules. Then, duplicate rules can be merged into one.
> 
> ```
> - name: Firebase Token
>   severity: high
>   type: pattern
>   values:
>    - (?P<value>[a-z0-9.-]+\.firebaseio\.com)
>    - (?P<value>[a-z0-9.-]+\.firebaseapp\.com)
>   filter_type: GeneralPattern
>   use_ml: false
>   validations: []
> ```

@gy741 

Thank you for suggestion!
Regrading "or" keyword that you suggested, we already using the `values:` to detecting multi line credentials.
Please check `AWS Multi` rule.

And in your case you can merge those rules into one line like below.

``` yaml
- name: AWS Client ID
  severity: high
  type: pattern
  values:
  - (?P<value>(ABIA|ACCA|AGPA|AIDA|AIPA|AKIA|ANPA|ANVA|AROA|APKA|ASCA|ASIA)[0-9A-Z]{16})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
```

**Review by csh519 — CHANGES_REQUESTED** [review]
Please add test case for `Firebase` and benchmark result on this PR.
We should to check how this change affects on benchmark result.

You can test benchmark with this repository [CredData#Benchmark](https://github.com/Samsung/CredData#Benchmark).

Thank you for contributing!

**Comment by meanrin** [comment]
> We should to check how this change affects on benchmark result.
> 
> You can test benchmark with this repository [CredData#Benchmark](https://github.com/Samsung/CredData#Benchmark).

This PR have no impact on benchmark results as we have no firebase examples in the dataset :(
So it would be a nice idea to later find repos with such examples

**Comment by gy741** [comment]
Hello @csh519 As per your advice, I combined the rules into one. 

Below is the result.

```
hack@hack:~$ python3 -m credsweeper --path /home/hack/strings.txt --rule /home/hack/config.yaml 
rule: Firebase io Token / severity: high / line_data_list: [line : '    <string name="firebase_database_url">https://api-project-615509201123.firebaseio.com</string>' / line_num : 1 / path : /home/hack/strings.txt / value: 'api-project-615509201123.firebaseio.com' / entropy_validation: True] / api_validation: NOT_AVAILABLE / ml_validation: NOT_AVAILABLE
rule: Firebase io Token / severity: high / line_data_list: [line : '    <string name="firebase_database_url">https://api-project-615509201123.firebaseapp.com</string>' / line_num : 2 / path : /home/hack/strings.txt / value: 'api-project-615509201123.firebaseapp.com' / entropy_validation: True] / api_validation: NOT_AVAILABLE / ml_validation: NOT_AVAILABLE
```

**Comment by csh519** [comment]
@gy741 
Thank you for commit.
But there is one more thing to do.. unit test. 😭 

Could you please add unit test regrading `Firebase` rule?
I think it would be good to add `test_firebase.py` into `tests/rules/` directory.

**Comment by gy741** [comment]
@csh519 Added unit testcase and modified rule name.

Can you confirm?

unit testcase:

```
python3 -m pytest --cov=credsweeper --cov-report=term-missing -s tests/rules/test_firebase_domain.py 


<frozen importlib._bootstrap_external>:640: ResourceWarning: unclosed file <_io.FileIO name='/home/hack/CredSweeper/credsweeper/log/credsweeper.log' mode='ab' closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
========================================================= test session starts =========================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/hack/CredSweeper/tests, configfile: pytest.ini
plugins: cov-3.0.0
collected 5 items                                                                                                                     

tests/rules/test_firebase_domain.py .....

---------- coverage: platform linux, python 3.8.10-final-0 -----------
Name                                                         Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------------
credsweeper/__init__.py                                          2      0   100%
credsweeper/__main__.py                                         32     32     0%   1-76
credsweeper/app.py                                             100    100     0%   1-178
credsweeper/common/__init__.py                                   1      0   100%
credsweeper/common/constants.py                                 34      0   100%
credsweeper/common/keyword_checklist.py                         12      1    92%   19
credsweeper/config/__init__.py                                   2      0   100%
credsweeper/config/config.py                                    16      0   100%
credsweeper/config/config_manager.py                            15      3    80%   16-18
credsweeper/credentials/__init__.py                              5      0   100%
credsweeper/credentials/candidate.py                            59     10    83%   29, 37, 45, 53, 61, 69, 81, 89, 92, 101
credsweeper/credentials/candidate_group_generator.py            22      8    64%   9, 13, 17, 20, 23, 26, 29, 32
credsweeper/credentials/candidate_key.py                        14      7    50%   10-13, 16, 19, 22
credsweeper/credentials/credential_manager.py                   24     13    46%   15, 23, 31, 39, 47, 56-65
credsweeper/credentials/line_data.py                           150     34    77%   44, 60, 68, 84, 92, 116, 124, 138, 169-172, 177-182, 188-193, 201-203, 211-215, 223-227, 230, 239
credsweeper/filters/__init__.py                                 22      0   100%
credsweeper/filters/filter.py                                    6      1    83%   18
credsweeper/filters/group/__init__.py                            6      0   100%
credsweeper/filters/group/general_keyword.py                     8      0   100%
credsweeper/filters/group/general_pattern.py                     6      0   100%
credsweeper/filters/group/group.py                              22      1    95%   20
credsweeper/filters/group/password_keyword.py                    8      0   100%
credsweeper/filters/group/pem_pattern.py                         8      0   100%
credsweeper/filters/group/url_credentials_group.py               8      0   100%
credsweeper/filters/line_specific_key_check.py                  13      2    85%   23, 26
credsweeper/filters/separator_unusual_check.py                  13      9    31%   22-33
credsweeper/filters/value_allowlist_check.py                    13      5    62%   25-31
credsweeper/filters/value_array_dictionary_check.py             11      5    55%   23-29
credsweeper/filters/value_blocklist_check.py                    12      7    42%   24-32
credsweeper/filters/value_camel_case_check.py                   13      5    62%   22-28
credsweeper/filters/value_dictionary_keyword_check.py           12      5    58%   20-24
credsweeper/filters/value_dictionary_value_length_check.py       9      5    44%   16-20
credsweeper/filters/value_entropy_check.py                       8      3    62%   17-19
credsweeper/filters/value_file_path_check.py                    12      8    33%   19-26
credsweeper/filters/value_first_word_check.py                   13      5    62%   24-28
credsweeper/filters/value_last_word_check.py                    11      5    55%   20-24
credsweeper/filters/value_length_check.py                        9      5    44%   16-20
credsweeper/filters/value_method_check.py                       11      5    55%   20-24
credsweeper/filters/value_not_allowed_pattern.py                13      5    62%   22-26
credsweeper/filters/value_pattern_filter.py                     46      9    80%   38, 52, 62, 76, 86, 99, 102, 105, 108
credsweeper/filters/value_similarity_check.py                   11      7    36%   17-24
credsweeper/filters/value_string_type_check.py                  18     11    39%   32-47
credsweeper/filters/value_token_check.py                        15      9    40%   24-36
credsweeper/filters/value_useless_word_check.py                 13      5    62%   27-33
credsweeper/filters/variable_check.py                           13      5    62%   22-28
credsweeper/logger/__init__.py                                   1      0   100%
credsweeper/logger/logger.py                                    30      3    90%   37, 49-50
credsweeper/ml_model/__init__.py                                 1      1     0%   1
credsweeper/ml_model/features.py                                90     90     0%   6-208
credsweeper/ml_model/ml_validator.py                           102    102     0%   1-121
credsweeper/rules/__init__.py                                    1      0   100%
credsweeper/rules/rule.py                                      107      8    93%   58, 68, 72, 97, 126, 141, 161, 179
credsweeper/scanner/__init__.py                                  1      0   100%
credsweeper/scanner/scan_type/__init__.py                        4      0   100%
credsweeper/scanner/scan_type/multi_pattern.py                  33     22    33%   35-58, 76-85
credsweeper/scanner/scan_type/pem_key_pattern.py                51     33    35%   39-50, 62-82, 99-104, 123-131
credsweeper/scanner/scan_type/scan_type.py                      47      6    87%   39, 54, 57-58, 82, 127
credsweeper/scanner/scan_type/single_pattern.py                 13      0   100%
credsweeper/scanner/scanner.py                                  40      7    82%   26-27, 61-65
credsweeper/utils/__init__.py                                    1      0   100%
credsweeper/utils/file_path_extractor.py                        53     53     0%   1-100
credsweeper/utils/util.py                                       37     13    65%   17-18, 41-45, 52-61
credsweeper/validations/__init__.py                              9      0   100%
credsweeper/validations/apply_validation.py                     30     30     0%   1-46
credsweeper/validations/github_token_validation.py              17      9    47%   31-46
credsweeper/validations/google_api_key_validation.py            24     16    33%   31-57
credsweeper/validations/google_multi_validation.py              18      9    50%   30-48
credsweeper/validations/mailchimp_key_validation.py             21     12    43%   30-51
credsweeper/validations/slack_token_validation.py               22     14    36%   28-46
credsweeper/validations/square_access_token_validation.py       17      9    47%   33-48
credsweeper/validations/square_client_id_validation.py          20     12    40%   29-46
credsweeper/validations/stripe_api_key_validation.py            23     14    39%   29-45
credsweeper/validations/validation.py                            8      1    88%   21
------------------------------------------------------------------------------------------
TOTAL                                                         1692    799    53%


========================================================== 5 passed in 0.61s ==========================================================

```

**Review by csh519 — APPROVED** [review]
Thank you for adding new rule `Firebase Domain`.

LGTM 👍

**Review by meanrin — APPROVED** [review]
LGTM, thank you for the new rule

**Pull request merged**
