### PR TITLE
Left barrier for short patterns which may be found in long base64 data

### PR DESCRIPTION
**Pull request by babenek**
Updated regex to skip small patterns which might be appear in long base64 encoded data.
The approach removes one wrong JWT credentials, looks like encrypted data:
```
 *   ciphertext: '6GeyJOCMluH-........
```
Updated experiment with the benchmark scores

### CODE REVIEW

**Review by csh519 — COMMENTED** [review]
If the left barrier needed.. how about the right barrier?
Could you please test about this?

**Comment by babenek** [comment]
@csh519 right barrier cannot be applied for various length patterns. '+' - is greedy and gets all symbols. 
I'll try check right barrier for fixed size only .

**Comment by babenek** [comment]
@csh519 https://github.com/Samsung/CredSweeper/pull/184/commits/e8eeae92c81ee1cb59c7cf5207a4e72c784b7e37
- only tests are updated due Square-secrets was recognized as Square-ID
- benchmark still the same.

**Review by csh519 — APPROVED** [review]
Thank you for improve patterns.

LGTM 👍

**Review by kmnls — APPROVED** [review]

**Pull request merged**
