### PR TITLE
Version up 1.4.2

### PR DESCRIPTION
**Pull request by csh519**
Version up 1.4.2

### CODE REVIEW

**Review by babenek — APPROVED** [review]
Please, merge the PR with REBASE or SQUASH. 
It will look much better in git workflow.

**Review by meanrin — APPROVED** [review]

**Comment by meanrin** [comment]
@csh519 @babenek 

> Please, merge the PR with REBASE or SQUASH.
> It will look much better in git workflow.

We can forbid "merge commits" in settings so it wont be a question in the future 
If i remember right, we often only allow "squash" in our other repos

**Comment by csh519** [comment]
> We can forbid "merge commits" in settings so it wont be a question in the future
> If i remember right, we often only allow "squash" in our other repos

@meanrin 

Yes, it's true. If then shall we just use "squash and merge"?

**Comment by meanrin** [comment]
@csh519 if it looks prettier in history and we use it in most other repositories, and no one is against
Why not, really 

I think we wanted to change this setting a whole year ago, but just forgot about it 
Same as with PR template T-T

**Comment by csh519** [comment]
@meanrin 

Oh.. yes i just forgot. I'll make a PR for those update and set the way of merge to "squash and merge".

**Comment by babenek** [comment]
@csh519 @meanrin 
It just my opinion. Development is easiest when multiple branches, but releases look good when merged in one line.
We have the check github_workflow
so, it fails all obsoleted PR, e.g. #191 and I have to rebase it.

**Comment by csh519** [comment]
@babenek 

Oh.. I merged #200 by "squash and merge".
May I merged wrong..?

**Pull request merged**
