### PR TITLE
Fix type errors in __main__.py

### PR DESCRIPTION
**Pull request by cuspymd**
I fixed below type hint errors in `__main__.py`
```
credsweeper/__main__.py:32: error: Function "argparse.ArgumentParser.parse_args" is not valid as a type
credsweeper/__main__.py:32: note: Perhaps you need "Callable[...]" or a callback protocol?
credsweeper/__main__.py:118: error: ArgumentParser.parse_args? has no attribute "log"
credsweeper/__main__.py:119: error: ArgumentParser.parse_args? has no attribute "log"
credsweeper/__main__.py:121: error: ArgumentParser.parse_args? has no attribute "path"
credsweeper/__main__.py:122: error: ArgumentParser.parse_args? has no attribute "path"
credsweeper/__main__.py:123: error: ArgumentParser.parse_args? has no attribute "path"
credsweeper/__main__.py:123: error: ArgumentParser.parse_args? has no attribute "skip_ignored"
credsweeper/__main__.py:124: error: ArgumentParser.parse_args? has no attribute "json_filename"
credsweeper/__main__.py:125: error: ArgumentParser.parse_args? has no attribute "diff_path"
credsweeper/__main__.py:126: error: ArgumentParser.parse_args? has no attribute "json_filename"
credsweeper/__main__.py:128: error: ArgumentParser.parse_args? has no attribute "diff_path"
credsweeper/__main__.py:129: error: Incompatible types in assignment (expression has type "PatchProvider", variable has type "TextProvider")                                                                                   
credsweeper/__main__.py:129: error: ArgumentParser.parse_args? has no attribute "diff_path"
credsweeper/__main__.py:132: error: ArgumentParser.parse_args? has no attribute "diff_path"
credsweeper/__main__.py:133: error: Incompatible types in assignment (expression has type "PatchProvider", variable has type "TextProvider")                                                                                   
credsweeper/__main__.py:133: error: ArgumentParser.parse_args? has no attribute "diff_path"                                                                             
```

### CODE REVIEW

**Review by babenek — COMMENTED** [review]
Could you add into ./tests/test_app.py a case when the error appears and fixed?

**Comment by cuspymd** [comment]
> Could you add into ./tests/test_app.py a case when the error appears and fixed?

It fixes not runtime errors but type hint errors.
This PR doesn't change logic of code, it changes only type hints.
So, I think unit test is not appropriate to verify fixes for type hint errors.

**Comment by babenek** [comment]
How the issue may be reproduced? 
pylint is used n the CI but only for errors and it did not found the errors.
Can we apply your checker?

**Review by Dmitriy-NK — APPROVED** [review]
LGTM!

**Pull request merged**
