### PR TITLE
Add publickey filtering

### PR DESCRIPTION
**Pull request by csh519**
## Description

There were some cases that have `public` or `pubkey` keyword in variable.

``` text
"encryptedPublicSharingKey": "abcde.........."
pdrendpoint_india_base64_pubkey: abcde..........
```

So I suggest to add `public` and `pubkey` to `VariableNotAllowedPatternCheck` filter.
And there are some changes regarding wrong class names and indent.

- Add `public` and `pubkey` keyword to `VariableNotAllowedPatternCheck` filter
- Fix indent
- Fix wrong class names

## How has this been tested?

- [X] Check the FP cases that variables have `public` or `pubkey` are filtered correctly
- [X] Pytest

### CODE REVIEW

**Comment by babenek** [comment]
Could you add a test sample which fails a test without the changes but passes with the PR?

**Review by babenek — DISMISSED** [review]
OK. ``publickey="MIGbMBAGByqG....`` now filtered.
Probably .crt extension might be removed from find_by_ext too.

**Comment by csh519** [comment]
> OK. `publickey="MIGbMBAGByqG....` now filtered. Probably .crt extension might be removed from find_by_ext too.

@babenek 

Thank you for suggestion!
I removed the `.crt` extension file from `find_by_ext` by 0a8f48b.

**Review by babenek — APPROVED** [review]
OK. Public keys are not suspicious credentials now.

**Review by kmnls — APPROVED** [review]

**Pull request merged**
