### PR TITLE
Fix repository url in doc

### PR DESCRIPTION
**Pull request by gy741**

### CODE REVIEW

**Review by csh519 — COMMENTED** [review]
Thank you for PR!

I wonder why you change all urls to use `https://` url..
Is there any profit to change like this?

**Comment by gy741** [comment]
Hello, @csh519 Either way is fine. 
How about the method below?

```
When paths to scan are entered, get the files in that paths and the files are excluded based on the list created by [config.json](../credsweeper/secret/config.json).
```

**Comment by csh519** [comment]
> Hello, @csh519 Either way is fine. How about the method below?
> 
> ```
> When paths to scan are entered, get the files in that paths and the files are excluded based on the list created by [config.json](../credsweeper/secret/config.json).
> ```

@gy741 

The link of `config.json` was wrong..  I'll add this fixes by other PR.
Thank you for finding!

**Comment by gy741** [comment]
@csh519 Other links must also be modified with relative paths.

**Comment by csh519** [comment]
> @csh519 Other links must also be modified with relative paths.

@gy741 

Opps.. I missed it.
I made PR #12 for this issue.

**Comment by csh519** [comment]
PR #12 is merged, so may I close this PR?

**Comment by csh519** [comment]
I'll close this PR.. If you have issue regrading this please make a new PR.

**Pull request closed without merging**
