### PR TITLE
Add tensorflow 2.7.0, 2.6.2 support

### PR DESCRIPTION
**Pull request by meanrin**
Allow tensorflow `2.6.2` and `2.7.0` instalstion
Both released 13 days ago: https://github.com/tensorflow/tensorflow/releases

TF `2.6.1` and `2.6.0` still have a bug that brakes `load_model` function

### CODE REVIEW

**Review by Dmitriy-NK — APPROVED** [review]
Thanks for update support libraries

**Comment by ARKAD97** [comment]
LGTM!

**Review by ARKAD97 — APPROVED** [review]
LGTM!

**Review by csh519 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
