### PR TITLE
MlValidator object is created once

### PR DESCRIPTION
**Pull request by babenek**
Speedup when Credsweeper object is created and used many times with ml_validation - skip multiple model load

### CODE REVIEW

**Review by csh519 — COMMENTED** [review]
Good point :eyes: 

But is there a case where ML models are created and executed many times?
I think it is same result in normal case.

**Comment by babenek** [comment]
During the model is created, there is heaviest process - model file loading.

**Comment by csh519** [comment]
> During the model is created, there is heaviest process - model file loading.

Yes, I know. But in this code `post_processing()` method just called once in normal execution scenario.. isn't it?

**Comment by babenek** [comment]
> 

in APP case - yes, but in API using - there might be variations...

**Review by csh519 — APPROVED** [review]
Thank you for explanation!

LGTM :+1:

**Review by Dmitriy-NK — APPROVED** [review]
No objection on my part.

**Pull request merged**
