### PR TITLE
Increase max line length to 8000

### PR DESCRIPTION
**Pull request by babenek**
## Description

Please include a summary of the change and which is fixed.

- Increase maximal line lengtht to 8000
- small slowdown for benchmark (2%)

## How has this been tested?

Please describe the tests that you ran to verify your changes.

- [x] UnitTest
- [x] Benchmark
- [x] TODO: rollback custom  benchmark reference after https://github.com/Samsung/CredData/pull/59

### CODE REVIEW

**Review by kmnls — DISMISSED** [review]
Agree

**Review by Yullia — DISMISSED** [review]

**Review by csh519 — APPROVED** [review]
Okay let's move up `MAX_LINE_LENGTH` to 8000.
But if the performance time increased abnormally, it can be reverted.

LGTM :+1:

**Comment by csh519** [comment]
@xDizzix @babenek 

Please monitor if this PR affects the internal service.

**Review by xDizzix — APPROVED** [review]
+

**Review by kmnls — APPROVED** [review]
Agree

**Pull request merged**
