### PR TITLE
Update docstrings according to Google Python Style Guide

### PR DESCRIPTION
**Pull request by Dmitriy-NK**
Update docstrings according to [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html).
Examples [here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

### CODE REVIEW

**Review by meanrin — DISMISSED** [review]
Small formatting changes to docstrings to make better automatic doc generation in Sphinx or Doxygen 
LGTM

**Review by csh519 — APPROVED** [review]
Thank you for update docstrings.

LGTM 👍

**Review by meanrin — APPROVED** [review]
Last commit removed redundant typing from few docstrings https://github.com/Samsung/CredSweeper/pull/49/commits/aa98d367fd5ecb02c76459b2d1326fb943c676fb
This text typing is not required, as type can be inferred from [typehints](https://docs.python.org/3/library/typing.html) in the scanner code. This docstring typing was recommended prior to the python3.5, as no syntax for a typehints in code existed 

Still LGTM

**Review by ARKAD97 — APPROVED** [review]
LGTM

**Review by csh519 — APPROVED** [review]

**Pull request merged**
