### PR TITLE
Slight changes for development

### PR DESCRIPTION
**Pull request by babenek**
## Description

Please include a summary of the change and which is fixed.

- Optimize ML validator creation - might help in multijob usage, e.g. #424
- Reorganize parent classes in DeepScanner to add new scanners in separated lines and reduce possible conflicts
- optimize file signature detection: startswith instead each element comparison

## How has this been tested?

Please describe the tests that you ran to verify your changes.

- [x] UnitTest
- [x] Benchmark - no benchmark impact

### CODE REVIEW

**Review by Yullia — DISMISSED** [review]

**Review by xDizzix — APPROVED** [review]
Good

**Comment by babenek** [comment]
Rollback ML optimization for #424 only

**Review by csh519 — APPROVED** [review]
New code block of `_use_ml_validation()` seems duplicated with `post_processing()`'s one.
But i assume it will be used on next PR.

LGTM :+1:

**Comment by babenek** [comment]
> New code block of `_use_ml_validation()` seems duplicated with `post_processing()`'s one. But i assume it will be used on next PR.
> 
> LGTM 👍

Partially, it is.
There is possibly case when the same value is available for ml but after grouping it will be skipped.

**Comment by true13** [comment]
Good

**Pull request merged**
