### PR TITLE
Add nonce, salt, certificate. Update pass, auth, key

### PR DESCRIPTION
**Pull request by meanrin**
- Add rules for Salt, Nonce, Certificate. Examples in tests is a modified credentials from the CredData
- Change Password rule from `password|passwd` to `pass` due to some samples that cannot be detected otherwise
- Add lookahead  to Auth and Key. With old way that was impossible to detect something like `keydocker = ...` as the letter `d` was a part of `[^word]` group. Lookahead approach fixes it

---------------------
Benchmark results:

Current main branch on CredData (after #32 PR with new model):
```
result_cnt : 4001, lost_cnt : 0, true_cnt : 3617, false_cnt : 384
credsweeper -> TP : 3617, FP : 384, TN : 19454315, FN : 966, FPR : 0.0000197382, FNR : 0.2107789657, PRC : 0.9040239940, RCL : 0.7892210343, F1 : 0.8427306617
```

This branch on CredData:
```
result_cnt : 4179, lost_cnt : 0, true_cnt : 3739, false_cnt : 440
credsweeper -> TP : 3739, FP : 440, TN : 19454259, FN : 844, FPR : 0.0000226166, FNR : 0.1841588479, PRC : 0.8947116535, RCL : 0.8158411521, F1 : 0.8534581146
```

### CODE REVIEW

**Review by ARKAD97 — APPROVED** [review]
LGTM!

**Review by Dmitriy-NK — APPROVED** [review]
Looks good. Thank you.

**Review by csh519 — COMMENTED** [review]
Thank you for fixes!

But I'm worried about benchmark result..
Could you please compare this changes with before?

**Comment by meanrin** [comment]
@csh519 , I included benchmark results in the description 

Please note that metrics is #32 description text was specifically reported from combined #32 and #33 changes. Not just #32 on itself
So "Current main branch" metric is exactly what #32 can achieve by itself (without this pr)

**Review by csh519 — APPROVED** [review]
@meanrin 

Thank you for comment.

LGTM 👍

**Pull request merged**
