### PR TITLE
Update KeywordPattern to more accuracy and cover "ENC(" case

### PR DESCRIPTION
**Pull request by csh519**
## Description

There are some cases that CredSweeper didn't catch all attributes(`key`, `separator`, `value`, and so on).
And `ENC(` case was one of them.
This PR improves `KeywordPattern` accuracy and help to catch `ENC(` case well too.

- Update `KeywordPattern` regex

## How has this been tested?

- [X] Tested with real `ENC(` cases that detected from CredSweeper

### CODE REVIEW

**Review by babenek — COMMENTED** [review]
Conflicts in benchmark scores have to be resolved ...

**Review by kmnls — COMMENTED** [review]
Could you please provide an unit test for this exact case?

**Comment by csh519** [comment]
> Conflicts in benchmark scores have to be resolved ...

@babenek 

I resolved the conflicts.
Please check [c89d03c](https://github.com/Samsung/CredSweeper/pull/214/commits/c89d03c0b4e5f97efc8c09e29773a49969dcd9b8).

**Comment by csh519** [comment]
> Could you please provide an unit test for this exact case?

@kmnls
I added `ENC(` and `ENC[` cases to unit test.
Please check [62e84c2](https://github.com/Samsung/CredSweeper/pull/214/commits/62e84c23b43d6b1b871fe51bd705c1011911307f).

**Review by babenek — APPROVED** [review]
LGTM.
Thank for good test samples

**Review by kmnls — APPROVED** [review]
Agree, this will reduce FP rate

**Pull request merged**
